package domain

const KeyPrefixLearningThermostat = "device"

type LearningThermostat struct {
	Bucket

	Value LearningThermostatValue `json:"value"`
}

type LearningThermostatValue struct {
	AltHeatDelivery                    string        `json:"alt_heat_delivery"`
	AltHeatSource                      string        `json:"alt_heat_source"`
	AltHeatX2Delivery                  string        `json:"alt_heat_x2_delivery"`
	AltHeatX2Source                    string        `json:"alt_heat_x2_source"`
	AutoAwayEnable                     bool          `json:"auto_away_enable"`
	AutoAwayReset                      bool          `json:"auto_away_reset"`
	AutoDehumEnabled                   bool          `json:"auto_dehum_enabled"`
	AutoDehumState                     bool          `json:"auto_dehum_state"`
	AuxHeatDelivery                    string        `json:"aux_heat_delivery"`
	AuxHeatSource                      string        `json:"aux_heat_source"`
	AuxLockoutLeaf                     int           `json:"aux_lockout_leaf"`
	AvailableLocales                   string        `json:"available_locales"`
	AwayTemperatureHigh                float64       `json:"away_temperature_high"`
	AwayTemperatureHighAdjusted        float64       `json:"away_temperature_high_adjusted"`
	AwayTemperatureHighEnabled         bool          `json:"away_temperature_high_enabled"`
	AwayTemperatureLow                 float64       `json:"away_temperature_low"`
	AwayTemperatureLowAdjusted         float64       `json:"away_temperature_low_adjusted"`
	AwayTemperatureLowEnabled          bool          `json:"away_temperature_low_enabled"`
	BackplateBslInfo                   string        `json:"backplate_bsl_info"`
	BackplateBslVersion                string        `json:"backplate_bsl_version"`
	BackplateModel                     string        `json:"backplate_model"`
	BackplateMonoInfo                  string        `json:"backplate_mono_info"`
	BackplateMonoVersion               string        `json:"backplate_mono_version"`
	BackplateSerialNumber              string        `json:"backplate_serial_number"`
	BackplateTemperature               float64       `json:"backplate_temperature"`
	BatteryLevel                       float64       `json:"battery_level"`
	CapabilityLevel                    float64       `json:"capability_level"`
	ClickSound                         string        `json:"click_sound"`
	CompressorLockoutLeaf              float64       `json:"compressor_lockout_leaf"`
	CoolingDelivery                    string        `json:"cooling_delivery"`
	CoolingSource                      string        `json:"cooling_source"`
	CoolingX2Delivery                  string        `json:"cooling_x2_delivery"`
	CoolingX2Source                    string        `json:"cooling_x2_source"`
	CoolingX3Delivery                  string        `json:"cooling_x3_delivery"`
	CoolingX3Source                    string        `json:"cooling_x3_source"`
	CountryCode                        string        `json:"country_code"`
	CreationTime                       int64         `json:"creation_time"`
	CurrentHumidity                    int           `json:"current_humidity"`
	CurrentScheduleMode                string        `json:"current_schedule_mode"`
	CurrentVersion                     string        `json:"current_version"`
	DehumidifierOrientationSelected    string        `json:"dehumidifier_orientation_selected"`
	DehumidifierState                  bool          `json:"dehumidifier_state"`
	DehumidifierType                   string        `json:"dehumidifier_type"`
	DemandChargeIcon                   bool          `json:"demand_charge_icon"`
	DeviceLocale                       string        `json:"device_locale"`
	DualFuelBreakpoint                 int           `json:"dual_fuel_breakpoint"`
	DualFuelBreakpointOverride         string        `json:"dual_fuel_breakpoint_override"`
	Eco                                Eco           `json:"eco"`
	EcoOnboardingNeeded                bool          `json:"eco_onboarding_needed"`
	EmerHeatDelivery                   string        `json:"emer_heat_delivery"`
	EmerHeatEnable                     bool          `json:"emer_heat_enable"`
	EmerHeatSource                     string        `json:"emer_heat_source"`
	ErrorCode                          string        `json:"error_code"`
	FanCapabilities                    string        `json:"fan_capabilities"`
	FanControlState                    bool          `json:"fan_control_state"`
	FanCoolingEnabled                  bool          `json:"fan_cooling_enabled"`
	FanCoolingReadiness                string        `json:"fan_cooling_readiness"`
	FanCoolingState                    bool          `json:"fan_cooling_state"`
	FanCurrentSpeed                    string        `json:"fan_current_speed"`
	FanDutyCycle                       int           `json:"fan_duty_cycle"`
	FanDutyEndTime                     int           `json:"fan_duty_end_time"`
	FanDutyStartTime                   int           `json:"fan_duty_start_time"`
	FanHeatCoolSpeed                   string        `json:"fan_heat_cool_speed"`
	FanMode                            string        `json:"fan_mode"`
	FanScheduleSpeed                   string        `json:"fan_schedule_speed"`
	FanTimerDuration                   int           `json:"fan_timer_duration"`
	FanTimerSpeed                      string        `json:"fan_timer_speed"`
	FanTimerTimeout                    int           `json:"fan_timer_timeout"`
	FarsightScreen                     string        `json:"farsight_screen"`
	FilterChangedDate                  int           `json:"filter_changed_date"`
	FilterChangedSetDate               int           `json:"filter_changed_set_date"`
	FilterReminderEnabled              bool          `json:"filter_reminder_enabled"`
	FilterReminderLevel                int           `json:"filter_reminder_level"`
	FilterReplacementNeeded            bool          `json:"filter_replacement_needed"`
	FilterReplacementThresholdSec      int           `json:"filter_replacement_threshold_sec"`
	FilterRuntimeSec                   int           `json:"filter_runtime_sec"`
	ForcedAir                          bool          `json:"forced_air"`
	GearThresholdHigh                  int           `json:"gear_threshold_high"`
	GearThresholdLow                   int           `json:"gear_threshold_low"`
	HasAirFilter                       bool          `json:"has_air_filter"`
	HasAltHeat                         bool          `json:"has_alt_heat"`
	HasAuxHeat                         bool          `json:"has_aux_heat"`
	HasDehumidifier                    bool          `json:"has_dehumidifier"`
	HasDualFuel                        bool          `json:"has_dual_fuel"`
	HasEmerHeat                        bool          `json:"has_emer_heat"`
	HasFan                             bool          `json:"has_fan"`
	HasFossilFuel                      bool          `json:"has_fossil_fuel"`
	HasHeatPump                        bool          `json:"has_heat_pump"`
	HasHotWaterControl                 bool          `json:"has_hot_water_control"`
	HasHotWaterTemperature             bool          `json:"has_hot_water_temperature"`
	HasHumidifier                      bool          `json:"has_humidifier"`
	HasX2AltHeat                       bool          `json:"has_x2_alt_heat"`
	HasX2Cool                          bool          `json:"has_x2_cool"`
	HasX2Heat                          bool          `json:"has_x2_heat"`
	HasX3Cool                          bool          `json:"has_x3_cool"`
	HasX3Heat                          bool          `json:"has_x3_heat"`
	HeatLinkConnection                 int           `json:"heat_link_connection"`
	HeatPumpAuxThreshold               int           `json:"heat_pump_aux_threshold"`
	HeatPumpAuxThresholdEnabled        bool          `json:"heat_pump_aux_threshold_enabled"`
	HeatPumpCompThreshold              float64       `json:"heat_pump_comp_threshold"`
	HeatPumpCompThresholdEnabled       bool          `json:"heat_pump_comp_threshold_enabled"`
	HeatX2Delivery                     string        `json:"heat_x2_delivery"`
	HeatX2Source                       string        `json:"heat_x2_source"`
	HeatX3Delivery                     string        `json:"heat_x3_delivery"`
	HeatX3Source                       string        `json:"heat_x3_source"`
	HeaterDelivery                     string        `json:"heater_delivery"`
	HeaterSource                       string        `json:"heater_source"`
	HeatpumpReady                      bool          `json:"heatpump_ready"`
	HeatpumpSavings                    string        `json:"heatpump_savings"`
	HeatpumpSetbackActive              bool          `json:"heatpump_setback_active"`
	HomeAwayInput                      bool          `json:"home_away_input"`
	HotWaterActive                     bool          `json:"hot_water_active"`
	HotWaterAwayActive                 bool          `json:"hot_water_away_active"`
	HotWaterAwayEnabled                bool          `json:"hot_water_away_enabled"`
	HotWaterBoilingState               bool          `json:"hot_water_boiling_state"`
	HumidifierState                    bool          `json:"humidifier_state"`
	HumidifierType                     string        `json:"humidifier_type"`
	HumidityControlLockoutEnabled      bool          `json:"humidity_control_lockout_enabled"`
	HumidityControlLockoutEndTime      int           `json:"humidity_control_lockout_end_time"`
	HumidityControlLockoutStartTime    int           `json:"humidity_control_lockout_start_time"`
	HvacPins                           string        `json:"hvac_pins"`
	HvacSafetyShutoffActive            bool          `json:"hvac_safety_shutoff_active"`
	HvacSmokeSafetyShutoffActive       bool          `json:"hvac_smoke_safety_shutoff_active"`
	HvacStagingIgnore                  bool          `json:"hvac_staging_ignore"`
	HvacWires                          string        `json:"hvac_wires"`
	IsFurnaceShutdown                  bool          `json:"is_furnace_shutdown"`
	KryptoniteRangeTestTimestamp       int           `json:"kryptonite_range_test_timestamp"`
	LastSoftwareUpdateUtcSecs          int           `json:"last_software_update_utc_secs"`
	Leaf                               bool          `json:"leaf"`
	LeafAwayHigh                       float64       `json:"leaf_away_high"`
	LeafAwayLow                        float64       `json:"leaf_away_low"`
	LeafScheduleDelta                  float64       `json:"leaf_schedule_delta"`
	LeafThresholdCool                  int           `json:"leaf_threshold_cool"`
	LeafThresholdHeat                  float64       `json:"leaf_threshold_heat"`
	LearningMode                       bool          `json:"learning_mode"`
	LocalIP                            string        `json:"local_ip"`
	LoggingPriority                    string        `json:"logging_priority"`
	LowerSafetyTemp                    float64       `json:"lower_safety_temp"`
	LowerSafetyTempEnabled             bool          `json:"lower_safety_temp_enabled"`
	MacAddress                         string        `json:"mac_address"`
	MaintBandLower                     float64       `json:"maint_band_lower"`
	MaintBandUpper                     float64       `json:"maint_band_upper"`
	MaxNighttimePreconditioningSeconds int           `json:"max_nighttime_preconditioning_seconds"`
	ModelVersion                       string        `json:"model_version"`
	NlclientState                      string        `json:"nlclient_state"`
	ObOrientation                      string        `json:"ob_orientation"`
	ObPersistence                      bool          `json:"ob_persistence"`
	OobInterviewCompleted              bool          `json:"oob_interview_completed"`
	OobStartupCompleted                bool          `json:"oob_startup_completed"`
	OobSummaryCompleted                bool          `json:"oob_summary_completed"`
	OobTempCompleted                   bool          `json:"oob_temp_completed"`
	OobTestCompleted                   bool          `json:"oob_test_completed"`
	OobWhereCompleted                  bool          `json:"oob_where_completed"`
	OobWifiCompleted                   bool          `json:"oob_wifi_completed"`
	OobWiresCompleted                  bool          `json:"oob_wires_completed"`
	PinCDescription                    string        `json:"pin_c_description"`
	PinGDescription                    string        `json:"pin_g_description"`
	PinObDescription                   string        `json:"pin_ob_description"`
	PinRcDescription                   string        `json:"pin_rc_description"`
	PinRhDescription                   string        `json:"pin_rh_description"`
	PinStarDescription                 string        `json:"pin_star_description"`
	PinW1Description                   string        `json:"pin_w1_description"`
	PinW2AuxDescription                string        `json:"pin_w2aux_description"`
	PinY1Description                   string        `json:"pin_y1_description"`
	PinY2Description                   string        `json:"pin_y2_description"`
	PostalCode                         string        `json:"postal_code"`
	PreconditioningActive              bool          `json:"preconditioning_active"`
	PreconditioningEnabled             bool          `json:"preconditioning_enabled"`
	PreconditioningReady               bool          `json:"preconditioning_ready"`
	ProID                              string        `json:"pro_id"`
	RadiantControlEnabled              bool          `json:"radiant_control_enabled"`
	RcsCapable                         bool          `json:"rcs_capable"`
	Rssi                               int           `json:"rssi"`
	SafetyState                        string        `json:"safety_state"`
	SafetyStateTime                    int           `json:"safety_state_time"`
	SafetyTempActivatingHvac           bool          `json:"safety_temp_activating_hvac"`
	ScheduleLearningReset              bool          `json:"schedule_learning_reset"`
	Schedules                          []interface{} `json:"schedules"`
	SerialNumber                       string        `json:"serial_number"`
	ShouldWakeOnApproach               bool          `json:"should_wake_on_approach"`
	SmokeShutoffSupported              bool          `json:"smoke_shutoff_supported"`
	StarType                           string        `json:"star_type"`
	SunlightCorrectionActive           bool          `json:"sunlight_correction_active"`
	SunlightCorrectionEnabled          bool          `json:"sunlight_correction_enabled"`
	SunlightCorrectionReady            bool          `json:"sunlight_correction_ready"`
	TargetHumidity                     int           `json:"target_humidity"`
	TargetHumidityEnabled              bool          `json:"target_humidity_enabled"`
	TemperatureLock                    bool          `json:"temperature_lock"`
	TemperatureLockHighTemp            float64       `json:"temperature_lock_high_temp"`
	TemperatureLockLowTemp             int           `json:"temperature_lock_low_temp"`
	TemperatureLockPinHash             string        `json:"temperature_lock_pin_hash"`
	TemperatureScale                   string        `json:"temperature_scale"`
	TimeToTarget                       int           `json:"time_to_target"`
	TimeToTargetTraining               string        `json:"time_to_target_training"`
	TouIcon                            bool          `json:"tou_icon"`
	TouchedBy                          TouchedBy     `json:"touched_by"`
	UpperSafetyTemp                    int           `json:"upper_safety_temp"`
	UpperSafetyTempEnabled             bool          `json:"upper_safety_temp_enabled"`
	WeaveDeviceIDSelfReported          string        `json:"weave_device_id_self_reported"`
	WhereID                            string        `json:"where_id"`
	WiringError                        string        `json:"wiring_error"`
	WiringErrorTimestamp               int           `json:"wiring_error_timestamp"`
	Y2Type                             string        `json:"y2_type"`
}

type Eco struct {
	Mode                string `json:"mode"`
	ModeUpdateTimestamp int    `json:"mode_update_timestamp"`
	TouchedBy           int    `json:"touched_by"` // TODO: Consider renaming to "TouchedByID".
}
